---

- name: Install vim wget git
  yum: pkg={{ item }} state=installed
  with_items:
  - vim
  - wget

- name: Check if Java has already been downloaded and unpacked
  stat:
    path: '{{ java_jdk_dir }}'
  register: dir

- name: Download Java JDK
  get_url:
    url: "{{ java_download_url }}"
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    dest: /tmp/{{ java_archive_name }}
  when: dir.stat.exists == False
  tags:
    - java_install

- name: Create Java directory
  file:
    name: "{{ java_root_dir }}"
    state: directory
  when: dir.stat.exists == False
  tags:
    - java_install

- name: Unpack Java JDK
  unarchive:
    src: /tmp/{{ java_archive_name }}
    dest: "{{ java_root_dir }}"
    copy: no
    owner: root
    group: root
  when: dir.stat.exists == False
  tags:
    - java_install

- name: Install Java alternatives
  alternatives:
    name: java
    link: /usr/bin/java
    path: '{{ java_jdk_dir }}/bin/java'
  tags:
    - java_install_alternatives

- name: Delete Java JDK tar.gz file
  file:
    path: /tmp/{{ java_archive_name }}
    state: absent
  tags:
    - java_cleanup

- name: Set fact java_8_installed
  set_fact:
    java_8_installed: true
  tags:
    - java_install
